### ISSUE TITLE
How to overwrite default base-web files

### ISSUE THREAD

**Issue by axtho** [yiisoft/yii-project-template#10]
I was thinking that one can overwrite the base template files (like views/layouts/main.php) by simply reproducing them in my new template structure (src/views/layouts/main.php). But it does not do that.

What is the idea here? I know that is early for docs, but that would be helpful to know how one can add and change stuff.

**Comment by axtho** [comment]
Any news on this?

**Comment by samdark** [comment]
@hiqsol could you write about it here? Later we'll convert it to docs.

**Comment by hiqsol** [comment]
This should be done through `Theme`.
But I doubt it should be done in the project template by default.

**Comment by samdark** [comment]
Yes, that's why I'm suggesting documenting it.

**Comment by axtho** [comment]
A little nudge on documentation here ... i have tried to follow Theme instructions from [here](https://www.yiiframework.com/doc/guide/2.0/en/output-theming) ... I also checked the comments in the Theme.php file.

I put the theming instructions under common.php:
```
return [
    'components' => [
        'view' => [
            'theme' => [
                'pathMap' => ['@app/views' => '@app/themes/basic'],
                'baseUrl' => '@web/themes/basic',
                'basePath' => '@web/themes/basic',
            ]
        ]
    ]
];
```
...
Yet, the rendered view file remains the one from yii-base-web.

Besides this ... does that mean that I have to configure every aspect (controllers, models, views, widgets, etc.) via Theme? Why not extend the required classes. Say I want to add to User, why not write my own user class and extend the one yii-base-web?

So, some documentation on this would be really helpful, as this seems quite different to how we used to do things (e.g. have the stuff we are working on in the top-level structure ... components/ models/ etc...).

**Comment by odai-alali** [comment]
Are there any updates regarding this issue somewhere? I tried to change the `controllerNamespace` to my customized `SiteController.php` and got this:
```
An Error occurred while handling another error:
yii\exceptions\InvalidRouteException: Unable to resolve the request "site/error". in /app/vendor/yiisoft/yii-core/src/base/Module.php:551
Stack trace:
#0 /app/vendor/yiisoft/yii-web/src/ErrorHandler.php(103): yii\base\Module->runAction('site/error')
#1 /app/vendor/yiisoft/yii-core/src/base/ErrorHandler.php(124): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#3 {main}
Previous exception:
yii\exceptions\InvalidRouteException: Unable to resolve the request "". in /app/vendor/yiisoft/yii-core/src/base/Module.php:551
Stack trace:
#0 /app/vendor/yiisoft/yii-web/src/Application.php(94): yii\base\Module->runAction('', Array)
#1 /app/vendor/yiisoft/yii-core/src/base/Application.php(544): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /app/web/index.php(14): yii\base\Application->run()
#3 /app/web/index.php(15): {closure}()
#4 {main}

Next yii\web\NotFoundHttpException: Page not found. in /app/vendor/yiisoft/yii-web/src/Application.php:106
Stack trace:
#0 /app/vendor/yiisoft/yii-core/src/base/Application.php(544): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /app/web/index.php(14): yii\base\Application->run()
#2 /app/web/index.php(15): {closure}()
#3 {main}
```

I am still not understanding what advantage @hiqsol composer plugin offers. (yes I've read the documentation). 

Wouldn't it be better to have a clear overview and a full control of my application configurations other than checking the output of the merged config and override the parts I want to change?

If I added `yii-base-api` and `yii-base-web` to my project template. Which config will override the other?. both contains identity and controllerNamespace config.

**Comment by schmunk42** [comment]
> IMHO, Wouldn't it be better to have a clear overview and a full control of my application configurations other than checking the output of the merged config and override the parts I want to change?

Actually seeing/having the merged configuration in a file is one of the advantages compared to the previous approach where configs were often merged on startup ... also there's room for improvement when it comes to readability of the create file.

Can you create a gist of your merged config?

**Comment by machour** [comment]
@odai-alali here's how I configured my app, working fine: https://github.com/machour/yii3-kitchen-sink/blob/master/config/web.php#L7

**Comment by odai-alali** [comment]
Thanks for the fast answer

https://gist.github.com/odai-alali/8062326a39358a86dc2703a16852f331

In this config I removed `yii-base-api` and tried to customize `SiteController.php`. 

This is the merge dump
```shell
root@1098dc3467a8:/app# composer du -v
Assembling config files
 - yiisoft/yii-project-template No version set (parsed as 1.0.0) [common,params,web]
    - yiisoft/yii-debug dev-master 947b366 [params,web,tests]
    - foxy/foxy dev-master d067b84
    - yiisoft/rbac dev-master 56f403d [params,common,tests]
    - yiisoft/log-target-file dev-master 3509b36
    - yiisoft/yii-console dev-master b79bac9 [params,console]
       - cebe/markdown dev-master eeb1bf6
    - yiisoft/yii-bootstrap4 dev-master c47c369 [tests]
       - yiisoft/yii-jquery dev-master 1c25792 [tests]
    - yiisoft/yii-dataview dev-master 620aa48
    - yiisoft/yii-base-web dev-master 7941fe4 [params,common,web]
       - hiqdev/composer-config-plugin dev-master 4f8d841
       - vlucas/phpdotenv 2.6.x-dev 2a7dcf7
          - symfony/polyfill-ctype dev-master 82ebae0
       - yiisoft/yii-swiftmailer dev-master 9d8d1df [common,tests]
          - swiftmailer/swiftmailer dev-master b22e508
             - symfony/polyfill-intl-idn v1.11.0
                - symfony/polyfill-php72 dev-master ab50dcf
             - symfony/polyfill-mbstring dev-master fe5e94c
             - symfony/polyfill-iconv dev-master f037ea2
             - egulias/email-validator 2.1.7
                - doctrine/lexer dev-master 4ab6ea7
       - yiisoft/active-record dev-master 3e92f61 [params,common,tests]
          - yiisoft/db dev-master 2fe2f65 [params,common,tests]
       - yiisoft/cache dev-master 5a9a606 [params,common]
          - psr/simple-cache dev-master 408d5ea
       - yiisoft/log dev-master 3d9e512 [params,common]
          - psr/log dev-master c4421fc
       - yiisoft/di dev-master c89d940
          - psr/container 1.0.0
       - yiisoft/yii-web dev-master 1b0e14e [params,web,tests]
          - psr/http-message dev-master f6561bf
          - yiisoft/view dev-master 206f58f [common,tests]
          - yiisoft/yii-core dev-master 578baf7 [defines,params,common,console,web,build,tests]
             - yiisoft/inflector dev-master a0b46d8
             - yiisoft/arrays dev-master f82b460
                - yiisoft/strings dev-master b0de650
Generated autoload files containing 0 classes
```

**Comment by odai-alali** [comment]
Thanks @machour. I did the same but not working. I am missing something here, will try to look deeper or just try another fresh installation.

**Comment by machour** [comment]
You're forgetting to declare your namespace in composer.json:

Add this section:
```
    "autoload": {
        "psr-4": {"app\\": "src"}
    },
```

**Comment by odai-alali** [comment]
Ahaa. It works 🤦‍♂ 

Thanks. I will try to add `yii-base-api` too and see how the merge is working, still banging my head to the wall with this

**Comment by schmunk42** [comment]
@machour Would the autoload info be part of the merged config somewhere or did you see it from the `composer.json` file?

**Comment by machour** [comment]
@schmunk42 saw it in the composer.json (was betting on this error ^^)

@odai-alali Don't worry, it can be **really** off-putting at first, but then it all makes a lot of sense. You will also forget to run `composer du` once or twice too :)

Don't hesitate to join our [slack](https://join.slack.com/t/yii/shared_invite/enQtMzQ4MDExMDcyNTk2LWUzN2RlZmJiMDdiZDIwOWI4M2U3ODYwOTRjZDk5MTY1ZWM3YTY5MTVkNzRiN2RlMWQxODA5N2ZmY2E5NWI2YTM) if you need more guidance!

**Comment by schmunk42** [comment]
Should the autoloading be part of the template? I think so.
