### ISSUE TITLE
Some thoughts and summaries about template

### ISSUE THREAD

**Issue by kids-return** [yiisoft/yii-project-template#12]
The first thing you can confirm is that you need to have three basic templates.
See: https://github.com/yiisoft/yii-base-web/issues/45
Need to ensure that each template can be minimized and run independently.
`yii-base-web` used (depends on `view` and `asset`,main site or admin panel)
`yii-base-api` used for (REST ful api,No need for `view` and `asset`, etc. )
`yii-base-cli` used for (cron jobs, message queue listeners,swoole tcp server,rpc server,etc.)

Guarantee that `yii-base-web` and `yii-base-api` can be combined with `yii-base-cli`
For example,
```json
    "require": {
        "yiisoft/yii-base-api": "^3.0@dev"
    },
    "require-dev": {
        "yiisoft/yii-base-cli": "^3.0@dev"
    }
```
![image](https://user-images.githubusercontent.com/4520936/48695521-54c06580-ec1a-11e8-872e-6385365f73c2.png)

Implement the same functions as [`yiisoft/yii2-app-basic`](https://github.com/yiisoft/yii2-app-basic) in the following way
```json
    "require": {
        "yiisoft/yii-rest": "^3.0@dev"
        "yiisoft/yii-base-web": "^3.0@dev"
        "yiisoft/yii-base-cli": "^3.0@dev"
    }
```
`yii-base-web` and `yii-base-api`, `web.php` will conflict, so only require `yii-rest`.

Another way is `yii-base-api` to use a separate entrance file.
Such as this
```
/src
/public
    index.php <- used config/web.php
    api.php <- used config/api.php
```
`config/api.php` does not affect the implementation of [`yiisoft/yii2-app-basic`](https://github.com/yiisoft/yii2-app-basic) 
```json
    "require": {
        "yiisoft/yii-rest": "^3.0@dev"
        "yiisoft/yii-base-web": "^3.0@dev"
        "yiisoft/yii-base-cli": "^3.0@dev"
    }
```
I am not sure if my understanding is right, but these are my ideal ways.

`yii-base-cli` I have implemented it, need to create it and initialize it, I will submit PR

This is an example of a tcp server based on `swoole`
![image](https://user-images.githubusercontent.com/4520936/48697018-7d4a5e80-ec1e-11e8-96cf-8904f2441c27.png)

**Comment by kids-return** [comment]
> Another way is `yii-base-api` to use a separate entrance file.

`yii-base-api` I prefer this way

**Comment by samdark** [comment]
@hiqsol what do you think?
