### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by axtho** [yiisoft/yii-project-template#19]
Hey guys,

Thanks for your awesome work on this framework.
Out of curiosity: is there a roadmap for this quick-template? 

I have tried to install it, and have as yet been unsuccessful. I followed the instructions in the readme, did not choose foxy, did a composer update and am still getting errors, like this one:

`[28-Nov-2018 13:52:12 UTC] An Error occurred while handling another error:
yii\di\exceptions\CircularReferenceException: Circular reference to "user" detected while building: user; dereferencing:  in /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/di/src/AbstractContainer.php:119
Stack trace:
#0 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/di/src/Container.php(55): yii\di\AbstractContainer->build('user')
#1 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/yii-core/src/base/Module.php(805): yii\di\Container->get('user')
#2 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/yii-core/src/base/Module.php(751): yii\base\Module->get('user')
#3 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/yii-base-web/src/views/layouts/main.php(44): yii\base\Module->__get('user')
#4 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/view/src/view/View.php(374): require('/Applications/M...')
#5 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/view/src/view/View.php(250): yii\view\View->renderPhpFile('/Applications/M...', Array)
#6 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/yii-web/src/Controller.php(112): yii\view\View->renderFile('/Applications/M...', Array, Object(yii\app\controllers\SiteController))
#7 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/yii-web/src/Controller.php(98): yii\web\Controller->renderContent('<div class="sit...')
#8 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/yii-web/src/ErrorAction.php(173): yii\web\Controller->render('error', Array)
#9 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/yii-web/src/ErrorAction.php(152): yii\web\ErrorAction->renderHtmlResponse()
#10 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/yii-core/src/base/Action.php(99): yii\web\ErrorAction->run()
#11 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/yii-core/src/base/Controller.php(160): yii\base\Action->runWithParams(Array)
#12 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/yii-core/src/base/Module.php(542): yii\base\Controller->runAction('error', Array)
#13 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/yii-web/src/ErrorHandler.php(103): yii\base\Module->runAction('site/error')
#14 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/yii-core/src/base/ErrorHandler.php(123): yii\web\ErrorHandler->renderException(Object(ReflectionException))
#15 [internal function]: yii\base\ErrorHandler->handleException(Object(ReflectionException))
#16 {main}
Previous exception:
ReflectionException: Class yii\rbac\CheckAccessInterface does not exist in /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/di/src/AbstractContainer.php:421
Stack trace:
#0 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/di/src/AbstractContainer.php(421): ReflectionParameter->getClass()
#1 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/di/src/AbstractContainer.php(335): yii\di\AbstractContainer->getDependencies('yii\\web\\User')
#2 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/di/src/AbstractContainer.php(185): yii\di\AbstractContainer->buildFromConfig(Array)
#3 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/di/src/AbstractContainer.php(131): yii\di\AbstractContainer->buildWithDefinition(Array, Array)
#4 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/di/src/Container.php(55): yii\di\AbstractContainer->build('user')
#5 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/yii-core/src/base/Module.php(805): yii\di\Container->get('user')
#6 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/yii-core/src/base/Module.php(751): yii\base\Module->get('user')
#7 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/yii-base-web/src/views/layouts/main.php(44): yii\base\Module->__get('user')
#8 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/view/src/view/View.php(374): require('/Applications/M...')
#9 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/view/src/view/View.php(250): yii\view\View->renderPhpFile('/Applications/M...', Array)
#10 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/yii-web/src/Controller.php(112): yii\view\View->renderFile('/Applications/M...', Array, Object(yii\app\controllers\SiteController))
#11 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/yii-web/src/Controller.php(98): yii\web\Controller->renderContent('<div class="sit...')
#12 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/yii-base-web/src/controllers/SiteController.php(63): yii\web\Controller->render('index')
#13 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/yii-core/src/base/InlineAction.php(56): yii\app\controllers\SiteController->actionIndex()
#14 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/yii-core/src/base/Controller.php(160): yii\base\InlineAction->runWithParams(Array)
#15 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/yii-core/src/base/Module.php(542): yii\base\Controller->runAction('', Array)
#16 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/yii-web/src/Application.php(94): yii\base\Module->runAction('', Array)
#17 /Applications/MAMP/htdocs/sib/srv/vendor/yiisoft/yii-core/src/base/Application.php(544): yii\web\Application->handleRequest(Object(yii\web\Request))
#18 /Applications/MAMP/htdocs/sib/srv/public/index.php(14): yii\base\Application->run()
#19 /Applications/MAMP/htdocs/sib/srv/public/index.php(15): {closure}()
#20 {main}
`
I am sure you have working instances ... for us it seems a high effort to test this for now.
Do you have a target, like Q1 2019, Q4 2018 ... to get this working so the wider public can play with it?

Thanks again.

**Comment by cebe** [comment]
Can you show the eact steps you are trying? We are currently changing a lot of things, so minior changes in what you do may result in another setup than what works already.

**Comment by axtho** [comment]
Actually I was just following the instructions from the README:

1. `composer create-project --prefer-dist --stability=dev yiisoft/yii-project-template myapp`
2. `composer require "wikimedia/composer-merge-plugin"`
3. `composer config repositories.ap '{"type": "composer", "url": "https://asset-packagist.org"}'`
4. `composer config extra.merge-plugin.include "vendor/*/*/composer.assets.json"`
5. `composer require yiisoft/yii-base-web`
6. navigate to `localhost/myapp/public`

This results in the above error (PHP 7.2.7, Apache 2.2.34)

**Comment by Vincent-X** [comment]
same errors:
```
[01-Dec-2018 15:02:21 UTC] An Error occurred while handling another error:
yii\di\exceptions\CircularReferenceException: Circular reference to "user" detected while building: user; dereferencing:  in /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/di/src/AbstractContainer.php:119
Stack trace:
#0 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/di/src/Container.php(55): yii\di\AbstractContainer->build('user')
#1 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/yii-core/src/base/Module.php(805): yii\di\Container->get('user')
#2 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/yii-core/src/base/Module.php(751): yii\base\Module->get('user')
#3 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/yii-base-web/src/views/layouts/main.php(44): yii\base\Module->__get('user')
#4 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/view/src/view/View.php(374): require('/Users/VincentX...')
#5 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/view/src/view/View.php(250): yii\view\View->renderPhpFile('/Users/VincentX...', Array)
#6 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/yii-web/src/Controller.php(112): yii\view\View->renderFile('/Users/VincentX...', Array, Object(yii\app\controllers\SiteController))
#7 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/yii-web/src/Controller.php(98): yii\web\Controller->renderContent('<div class="sit...')
#8 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/yii-web/src/ErrorAction.php(173): yii\web\Controller->render('error', Array)
#9 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/yii-web/src/ErrorAction.php(152): yii\web\ErrorAction->renderHtmlResponse()
#10 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/yii-core/src/base/Action.php(99): yii\web\ErrorAction->run()
#11 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/yii-core/src/base/Controller.php(160): yii\base\Action->runWithParams(Array)
#12 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/yii-core/src/base/Module.php(542): yii\base\Controller->runAction('error', Array)
#13 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/yii-web/src/ErrorHandler.php(103): yii\base\Module->runAction('site/error')
#14 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/yii-core/src/base/ErrorHandler.php(123): yii\web\ErrorHandler->renderException(Object(ReflectionException))
#15 [internal function]: yii\base\ErrorHandler->handleException(Object(ReflectionException))
#16 {main}
Previous exception:
ReflectionException: Class yii\rbac\CheckAccessInterface does not exist in /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/di/src/AbstractContainer.php:426
Stack trace:
#0 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/di/src/AbstractContainer.php(426): ReflectionParameter->getClass()
#1 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/di/src/AbstractContainer.php(340): yii\di\AbstractContainer->getDependencies('yii\\web\\User')
#2 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/di/src/AbstractContainer.php(186): yii\di\AbstractContainer->buildFromConfig('user', Array)
#3 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/di/src/AbstractContainer.php(131): yii\di\AbstractContainer->buildWithDefinition('user', Array, Array)
#4 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/di/src/Container.php(55): yii\di\AbstractContainer->build('user')
#5 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/yii-core/src/base/Module.php(805): yii\di\Container->get('user')
#6 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/yii-core/src/base/Module.php(751): yii\base\Module->get('user')
#7 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/yii-base-web/src/views/layouts/main.php(44): yii\base\Module->__get('user')
#8 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/view/src/view/View.php(374): require('/Users/VincentX...')
#9 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/view/src/view/View.php(250): yii\view\View->renderPhpFile('/Users/VincentX...', Array)
#10 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/yii-web/src/Controller.php(112): yii\view\View->renderFile('/Users/VincentX...', Array, Object(yii\app\controllers\SiteController))
#11 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/yii-web/src/Controller.php(98): yii\web\Controller->renderContent('<div class="sit...')
#12 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/yii-base-web/src/controllers/SiteController.php(63): yii\web\Controller->render('index')
#13 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/yii-core/src/base/InlineAction.php(56): yii\app\controllers\SiteController->actionIndex()
#14 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/yii-core/src/base/Controller.php(160): yii\base\InlineAction->runWithParams(Array)
#15 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/yii-core/src/base/Module.php(542): yii\base\Controller->runAction('', Array)
#16 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/yii-web/src/Application.php(94): yii\base\Module->runAction('', Array)
#17 /Users/VincentX/Code/PHP/yii-app/vendor/yiisoft/yii-core/src/base/Application.php(544): yii\web\Application->handleRequest(Object(yii\web\Request))
#18 /Users/VincentX/Code/PHP/yii-app/public/index.php(14): yii\base\Application->run()
#19 /Users/VincentX/Code/PHP/yii-app/public/index.php(15): {closure}()
#20 {main}
$_SERVER = [
    'UNIQUE_ID' => 'XAKifcCoH8IAATdzHwQAAAAD',
    'HTTP_HOST' => 'yiiapp.local',
    'HTTP_CONNECTION' => 'keep-alive',
    'HTTP_CACHE_CONTROL' => 'max-age=0',
    'HTTP_UPGRADE_INSECURE_REQUESTS' => '1',
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36',
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
    'HTTP_ACCEPT_LANGUAGE' => 'zh-CN,zh;q=0.9',
    'PATH' => '/usr/bin:/bin:/usr/sbin:/sbin',
    'SERVER_SIGNATURE' => '',
    'SERVER_SOFTWARE' => 'Apache',
    'SERVER_NAME' => 'yiiapp.local',
    'SERVER_ADDR' => '127.0.0.1',
    'SERVER_PORT' => '80',
    'REMOTE_ADDR' => '127.0.0.1',
    'DOCUMENT_ROOT' => '/Users/VincentX/Code/PHP/yii-app/public',
    'SERVER_ADMIN' => 'you@example.com',
    'SCRIPT_FILENAME' => '/Users/VincentX/Code/PHP/yii-app/public/index.php',
    'REMOTE_PORT' => '61265',
    'GATEWAY_INTERFACE' => 'CGI/1.1',
    'SERVER_PROTOCOL' => 'HTTP/1.1',
    'REQUEST_METHOD' => 'GET',
    'QUERY_STRING' => '',
    'REQUEST_URI' => '/',
    'SCRIPT_NAME' => '/index.php',
    'PHP_SELF' => '/index.php',
    'REQUEST_TIME_FLOAT' => 1543676541.513,
    'REQUEST_TIME' => 1543676541,
    'argv' => [],
    'argc' => 0,
]
```

**Comment by axtho** [comment]
Todays `composer update` produces a working environment
