### ISSUE TITLE
Error Install Yii-Project-Template

### ISSUE THREAD

**Issue by terabytesoftw** [yiisoft/yii-project-template#24]
**Install:**

` composer create-project --prefer-dist --stability=dev yiisoft/yii-project-template .`

What steps will reproduce the problem ?

If we install only the package this error occurs.

```
( ! ) Fatal error: Uncaught ReflectionException: Class app does not exist in /home/domain/public_html/vendor/yiisoft/di/src/AbstractContainer.php on line 417
--

1 | 0.2009 | 356520 | {main}( ) | .../index.php:0
2 | 0.2010 | 356840 | {closure:/home/domain/public_html/public/index.php:7-15}( ) | .../index.php:15
3 | 0.2018 | 381832 | yii\di\Container->get( ) | .../index.php:14
4 | 0.2018 | 381832 | yii\di\Container->build( ) | .../Container.php:55
5 | 0.2018 | 382208 | yii\di\Container->buildWithDefinition( ) | .../AbstractContainer.php:131
6 | 0.2018 | 382208 | yii\di\Container->buildFromConfig( ) | .../AbstractContainer.php:186
7 | 0.2018 | 382584 | yii\di\Container->getDependencies( ) | .../AbstractContainer.php:340
```

### What is the expected result?

You should give a warning or exception indicating that you must install the packages web, api, or console.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 3.0.
| PHP version      | 7.1 
| Operating system | Centos 7.0

**Comment by hiqsol** [comment]
I propose to create `yii-web-template` for simple all-in-one template that anyone without any experience could install with single command without reading any docs. While leaving this package as a template for experienced users. At the moment I think we can't satisfy both audiences with single package. When we'll be able to achieve it we'll merge them back.

**Comment by terabytesoftw** [comment]
I understand how to install:

`composer require yiisoft/yii-base-web`

But you could add in the index to detect if the web, api or console packages are installed and give a warning.

**Comment by hiqsol** [comment]
I know you understand :)
But when I started yii-app-template I wanted it to be installable in one "click".

**Comment by terabytesoftw** [comment]
If your web application was perfect, I really do not understand what happened, in fact I have one that I am going to publish based on his work that was excellent with some modifications.

In yii2 we could detect the extensions installed with Yii::$app->extensions['repo/extension'] in Yii3 its posible ?
