### ISSUE TITLE
Asset dependencies

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii-project-template#26]
This commit re-added the asset dependencies we've removed earlier:
- https://github.com/yiisoft/yii-project-template/commit/83f1a02369d416d9e83338421a4a591bfd653722

This leads currently to the fact that `npm` is required through `foxy`. To me the project template would be cleaner and better designed if we do not have this by default.

CC: @samdark

**Comment by hiqsol** [comment]
We've discussed it with @samdark  and @SilverFire.
We prefer to have the project template completely working from a single step install.

Further improvements can include:
- add some minimal assets directly in the project template and remove yii-bootstrap4 and foxy requires
- and/or add documentation on how to change assets setup

**Comment by schmunk42** [comment]
> We prefer to have the project template completely working from a single step install.
> ...
> add some minimal assets directly in the project template and remove yii-bootstrap4 and foxy requires

There are minimal assets in the `yii-base-web` repo.
- https://github.com/yiisoft/yii-base-web/blob/master/public/css/site.css

**Comment by samdark** [comment]
Asset dependencies should be removed.

**Comment by samdark** [comment]
I guess it could be debug extension...

**Comment by samdark** [comment]
1. src/views/site/contact.php:9:use yii\bootstrap4\ActiveForm;
2. src/views/site/login.php:10:use yii\bootstrap4\ActiveForm;

in yii-base-web should be replaced with non-bootstrap AR.
