### ISSUE TITLE
Make project template more developer friendly

### ISSUE THREAD

**Issue by lubosdz** [yiisoft/yii-project-template#29]
After installing it's unclear how developer should start prototyping his new application, e.g. where should he place PHP files if he does not want to touch `/vendor/*` files ? 

In Yii2 it was [obvious ](https://github.com/yiisoft/yii2-app-basic)- there were directories like `/controllers/`, `/models/` etc.

In Yii 3 it's not obvious.

Would it be possible to add such an directory `app/` with 2-3 PHP files (1 controller + 1 view) so that developer knows instantly where to start? Or did I miss some documentation about this?

**Comment by samdark** [comment]
Yes. It's a good idea.

**Comment by machour** [comment]
The project template is, for now, designed to be a barebone template.
This is still under discussion, and we will probably end up proposing more user friendly templates.

See also:
- this forum thread: https://forum.yiiframework.com/t/basic-template-vs-new-yii-3-0-template/123978/33 (with this nice suggestion: https://forum.yiiframework.com/t/basic-template-vs-new-yii-3-0-template/123978/17?u=machour)
- this comment: https://github.com/yiisoft/yii-project-template/issues/24#issuecomment-449859476

**Comment by lubosdz** [comment]
Great, thanx!
Yes - template configurator would be cool, I have already read it.

If you will create new template, please consider also decreasing complexity in some parts, e.g. index.php:
* in Yii 2 it was clear [which config file](https://github.com/yiisoft/yii2-app-basic/blob/master/web/index.php#L10) is being loaded
* in Yii 3 it's hard to guess what does 
`$container = new Container(require Builder::path('web'));` 
resolves to. 

There is also useless cyclomatic [complexity](https://github.com/yiisoft/yii-project-template/blob/master/public/index.php#L7) here & there like using anonymous lambda functions which add extra processor & memory overhead (purpose is probably preventing global variable scopes ? - could be discussed if it's beneficial).
