### ISSUE TITLE
installing yii-base-cli sets wrong aliases

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii-project-template#30]
When I install `yii-base-cli` I get an alias in `web.php`

    '@yii/app' => 'vendor/yiisoft/yii-base-cli/src'

I think the autoloading here is wrong: https://github.com/yiisoft/yii-base-cli/blob/master/composer.json#L40
It should be removed.

Also, do we need the automatic assembly of `aliases` via config plugin?
Could it be disabled?

CC: @hiqsol

**Comment by hiqsol** [comment]
1. quickfixed namespace https://github.com/yiisoft/yii-base-cli/commit/cb74b1209cfe08ce9ea08e0c091e00011c700cc7
2. automatic aliases assembly was in yii2 so I have kept it in composer-config-plugin. It could be removed of course. But usually, it creates no problems while it is useful.
