### ISSUE TITLE
move base-web dependencies to yii-base-web composer.json

### ISSUE THREAD

**Issue by schmasterz** [yiisoft/yii-project-template#35]
Since yii-project-template is to be a barebone template, may be it is not a bad idea to move 
```
"yiisoft/yii-dataview": "^3.0@dev",
"yiisoft/yii-bootstrap4": "^3.0@dev",
"yiisoft/yii-jquery": "^3.0@dev"
```
to yii-base-web composer.json, and to remove yii-base-web as dependency in yii-project-template

**Comment by schmasterz** [comment]
Related to #26

**Comment by machour** [comment]
It's the other way around actually. We want yii-base-xxx to be dependencies free, and projects to be built on top of that. 

The provided project is for now using jQuery/bootstrap, this will change in the future, or maybe more project templates will be added for other combinations.

**Comment by schmunk42** [comment]
I agree to @schmasterz, the project template should be free of those deps, they rather belog to yii-base-web.

**Comment by machour** [comment]
> and to remove yii-base-web as dependency in yii-project-template

I didn't read that part 😅 Makes more sense.

But in that case, what exactly is "yii-base-web" ? a bootstrap/jquery project template ?

**Comment by schmunk42** [comment]
> But in that case, what exactly is "yii-base-web" ? a bootstrap/jquery project template ?

That's a never ending discussion ;) 

I'd be fine with the fact that a **yii-base-web** contains jQuery and BS4. 

There could also be a **yii-base-web-someothercoolcssframework** or **yii-base-vue**. Can be anything.

**Comment by schmunk42** [comment]
Related: https://github.com/yiisoft/yii-project-template/issues/43

I think we should strip down deps here to an absolute minimum.

Eg. removing those from https://github.com/yiisoft/yii-project-template/commit/83f1a02369d416d9e83338421a4a591bfd653722

CC: @hiqsol

**Comment by hiqsol** [comment]
> I think we should strip down deps here to an absolute minimum.

agree
