### ISSUE TITLE
Error on fresh installation: no log target 

### ISSUE THREAD

**Issue by sup-ham** [yiisoft/yii-project-template#36]
I'm getting this error message after run ```vendor/bin/yii serve``` and also found in apache error.log file
>[Tue Apr 30 12:16:04.371657 2019] [php7:error] [pid 17703] [client 127.0.0.1:52428] PHP Fatal error:  Uncaught Psr\\Log\\InvalidArgumentException: You must provide an instance of \\Yiisoft\\Log\\Target. in /media/xubuntux/c/xampp/htdocs/yii3-web/vendor/yiisoft/log/src/Logger.php:125\nStack trace:\n#0 /media/xubuntux/c/xampp/htdocs/yii3-web/vendor/yiisoft/log/src/Logger.php(87): Yiisoft\\Log\\Logger->setTargets(Array)\n#1 [internal function]: Yiisoft\\Log\\Logger->__construct(Array)\n#2 /media/xubuntux/c/xampp/htdocs/yii3-web/vendor/yiisoft/di/src/AbstractContainer.php(358): ReflectionClass->newInstanceArgs(Array)\n#3 /media/xubuntux/c/xampp/htdocs/yii3-web/vendor/yiisoft/di/src/AbstractContainer.php(189): yii\\di\\AbstractContainer->buildFromConfig('logger', Array)\n#4 /media/xubuntux/c/xampp/htdocs/yii3-web/vendor/yiisoft/di/src/AbstractContainer.php(131): yii\\di\\AbstractContainer->buildWithDefinition('logger', Array, Array)\n#5 /media/xubuntux/c/xampp/htdocs/yii3-web/vendor/yiisoft/di/src/Container.php(55): yii\\di\\AbstractContainer->build('logger')\n#6 /media/xubuntux/c/xampp/htdocs/yii3-web/vendor/yiisoft/yii-core/src/base/M in /media/xubuntux/c/xampp/htdocs/yii3-web/vendor/yiisoft/log/src/Logger.php on line 125

It seem missing log target in the logger configs 
So I  tried  add logger config into application template. 
This copied from yiisoft/log configuration with addition log target
~~~
    'logger' => [
        '__class' => Yiisoft\Log\Logger::class,
        '__construct()' => [
            'targets' => [
                ['__class' => 'Yiisoft\Log\FileTarget']
            ],
        ],
        'traceLevel' => $params['logger.traceLevel'],
    ],
~~~
and ```composer du``` of course. but it  seem not working.

**Comment by machour** [comment]
Hi,

This is due to the fact that currently DI doesn't inspect a constructor parameter array entries.
Until it's implemented (or decided otherwise), you can use a callable for the definition:

```php
    'logger' => function () {
        return new \Yiisoft\Log\Logger([
            new Yiisoft\Log\FileTarget("/tmp/log.txt")
        ]);
    }
```

Can you check if it works for you, and open a PR with this change if it works?

**Comment by suphm** [comment]
Found that the Logger->setTargets() checks for LogTarget instances meanwhile it receives DI definitions

**Comment by terabytesoftw** [comment]
I have tried this solution and I can not make the log work, as they solved it.
