### ISSUE TITLE
Uncaught yii\di\exceptions\NotFoundException: No definition for Psr\Http\Message\ServerRequestFactoryInterface in /private/var/www/yii3-rest/vendor/yiisoft/di/src/Container.php:149

### ISSUE THREAD

**Issue by prawee** [yiisoft/yii-project-template#38]
when i'm installation by
>  composer create-project --prefer-dist --stability=dev yiisoft/yii-project-template myapp
> cd myapp
> vendor/bin/yii -p 8081

after run server 

`127.0.0.1:58304 [200]: / - Uncaught yii\di\exceptions\NotFoundException: No definition for Psr\Http\Message\ServerRequestFactoryInterface in /private/var/www/yii3-rest/vendor/yiisoft/di/src/Container.php:149`

**Comment by samdark** [comment]
Already fixed.

**Comment by schmunk42** [comment]
@samdark How did you fix this? I am getting this (again) with the project-template.

**Comment by samdark** [comment]
Updated dependencies and constraints. Then did composer update.

**Comment by schmunk42** [comment]
Fixed my issue by adding config options.

Related: https://github.com/yiisoft/yii-base-web/issues/76
