### ISSUE TITLE
Is there a way to install yii3 without npm?

### ISSUE THREAD

**Issue by nd4c** [yiisoft/yii-project-template#43]
### What steps will reproduce the problem?
composer create-project --prefer-dist --stability=dev yiisoft/yii-project-template yii3

### What is the expected result?
A new yii3 website

### What do you get instead?
An error:
  - Installing foxy/foxy (dev-master dca69a7): Loading from cache
  [Foxy\Exception\RuntimeException]      
  The binary of "npm" must be installed  

### Additional info
I would prefer a lamp stack.

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 
| Operating system |

**Comment by samdark** [comment]
Try https://github.com/yiisoft/yii-demo for now. We're going to re-make template.

**Comment by nd4c** [comment]
Wow - quick reply!  OK - I'll check it out.  Thanks!

**Comment by schmunk42** [comment]
Did you also try option a) here: https://github.com/yiisoft/yii-project-template#web-application

**Comment by nd4c** [comment]
@schmunk42 
I didn't actually try it, but I did look at the composer.json file and it listed foxy/foxy which was causing the problem.  So I assumed I'd have the same issue.

**Comment by schmunk42** [comment]
If you do not have `npm` you have to remove `foxy/foxy` from `composer.json` and run

```
composer require "wikimedia/composer-merge-plugin"
composer config repositories.ap '{"type": "composer", "url": "https://asset-packagist.org"}'
composer config extra.merge-plugin.include "vendor/*/*/composer.assets.json"
```

Side question: Do you need JS packages at all?

**Comment by nd4c** [comment]
OK - I'll try that.

I'm not really a big fan of js frameworks - they are nice - definitely "cool" but I don't really need them at the moment.  I use Yii for a RIA that has extensive business/domain logic - most everything has to be done server side.   I like jQuery - it helps with the UI and is easy to "patch" in where needed.   I did have to build a js frontend to integrate with an esri backend - I obviously had to their libraries, but the frontend was from scratch - very lightweight.

**Comment by nd4c** [comment]
I tried https://github.com/yiisoft/yii-demo and that is working.

For this project I tried schmunk42's suggestions.  Composer ran fine.  It did give a warning:
Package yiisoft/yii-core is abandoned, you should avoid using it. Use yiisoft/yii-web instead.

Also when running the page (virtual host in apache) the error log has:
```
[Thu Oct 17 10:10:21.869995 2019] [php7:notice] [pid 9638] [client 127.0.0.1:41870] 
PHP Fatal error:  Uncaught ReflectionException: 
Class app does not exist in /var/www/html/yii3/vendor/yiisoft/factory/src/Resolvers/ClassNameResolver.php:22
Stack trace:
#0 /var/www/html/yii3/vendor/yiisoft/factory/src/Resolvers/ClassNameResolver.php(22): ReflectionClass->__construct('app')
#1 /var/www/html/yii3/vendor/yiisoft/factory/src/Definitions/ArrayBuilder.php(78): Yiisoft\\Factory\\Resolvers\\ClassNameResolver->resolveConstructor('app')
#2 /var/www/html/yii3/vendor/yiisoft/factory/src/Definitions/ArrayBuilder.php(18): Yiisoft\\Factory\\Definitions\\ArrayBuilder->getDependencies('app')
#3 /var/www/html/yii3/vendor/yiisoft/factory/src/Definitions/ArrayDefinition.php(74): Yiisoft\\Factory\\Definitions\\ArrayBuilder->build(Object(Yiisoft\\Di\\Container), Object(Yiisoft\\Factory\\Definitions\\ArrayDefinition))
#4 /var/www/html/yii3/vendor/yiisoft/di/src/Container.php(133): Yiisoft\\Factory\\Definitions\\ArrayDefinition->resolve(Object(Yiisoft\\Di\\Container), Array)
#5 /var/www/html/yii3/vendor/yiisoft/di/src/Container.php(113): Yiisoft\\Di\\Co in /var/www/html/yii3/vendor/yiisoft/factory/src/Resolvers/ClassNameResolver.php on line 22
```

**Comment by nd4c** [comment]
I just realized that this project is just the template - which would explain the error.  I'll try the different console and web packages.
