### ISSUE TITLE
I got error when i installing yii3 with composer..

### ISSUE THREAD

**Issue by bilginnet** [yiisoft/yii-project-template#44]
### What steps will reproduce the problem?

I got error when i installing yii3 with composer..

Code: 
composer create-project --prefer-dist --stability=dev yiisoft/yii-project-template yii3.app

### What is the expected result?
  [InvalidArgumentException]
  Could not find package yiisoft/yii-project-template with stability dev in a version installable using your PHP version 7.3.11.

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 3.*?
| PHP version      |   7.3.11
| Operating system | Windows 10 - xampp

**Comment by samdark** [comment]
Start with yiisoft/yii-demo package for now.

**Comment by samdark** [comment]
Also, PHP version 7.3.11 is not enough. 7.4 is required.

**Comment by schmunk42** [comment]
Should be fixed by https://github.com/yiisoft/yii-project-template/pull/46
