### ISSUE TITLE
Config yii-debug, yii-log.

### ISSUE THREAD

**Issue by tecnoterabyte** [yiisoft/yii-project-template#5]
Hi, i have configured yii-debug and yii-log, but debug is not displayed and logger does not give any record,

```
common.php

<?php

return [
    'bootstrap' => ['debug'],
    'debug' => [
        '__class' => yii\debug\Module::class,
        // uncomment and adjust the following to add your IP if you are not connecting from localhost.
        'allowedIPs' => ['127.0.0.1'],
    ],
    'logger' => [
        'targets' => [
		[
		    '__class' => yii\log\FileTarget::class,
		    'levels' => ['error', 'warning'],
		],
	],
    ],
];
```

After modifying use composer du, to rebuild in config,

Thks,

**Comment by hiqsol** [comment]
Yeap. It's not completely fixed yet.
To be done soon.

**Comment by tecnoterabyte** [comment]
Ok, very good ,is there any way to be able to see the log for errors and help debug this is possible ?

Thks,

**Comment by hiqsol** [comment]
Sorry, didn't understand your question.

**Comment by tecnoterabyte** [comment]
@hiqsol There is some way to enable debug or log to see the errors
