### ISSUE TITLE
yii-core is abandoned

### ISSUE THREAD

**Issue by mbunyan** [yiisoft/yii-project-template#50]
### What steps will reproduce the problem?
run composer create-project as per instruction

### What is the expected result?
No errors (a few maybe!!)
### What do you get instead?
```Package yiisoft/yii-core is abandoned, you should avoid using it. Use yiisoft/yii-web instead.```

### Additional info
composer.lock is significantly out of date and requires run composer update which fixes 46 updates

yiisoft/yii-web is cloned, but yii-core remains

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 7.4
| Operating system | Win 10

**Comment by samdark** [comment]
Yes. This package should be deprecated and removed.

Please use yiisoft/yii-demo for now.
