### ISSUE TITLE
Using create-project pulls old files

### ISSUE THREAD

**Issue by axtho** [yiisoft/yii-project-template#7]
When following the instructions to install via `composer create-project` I get an old version of the template (with yii-app still as the base web). I have cleared the composer cache already, but it still pulled the old version.

**Comment by hiqsol** [comment]
There was an error in the README.
The package is renamed to `yii-project-template`.
So proper command to create the project is:

```
composer create-project --prefer-dist --stability=dev yiisoft/yii-project-template myapp
```
