### ISSUE TITLE
Multiple core packages in vendor

### ISSUE THREAD

**Issue by axtho** [yiisoft/yii-project-template#9]
A clean install will yield the following scenario: two yii core packages will be installed, one called "core" (the old convention) and one called "yii-core" (I suppose that is the right one).

I have removed the vendor folder and the lock file, also cleared the composer cache before a new install. The issue remains.

It also appears that the "old" package gets loaded into the application:
```
#24 /Applications/MAMP/htdocs/hack/y3/vendor/yiisoft/core/src/base/Application.php(525): yii\web\Application->handleRequest(Object(yii\web\Request))
#25 /Applications/MAMP/htdocs/hack/y3/public/index.php(14): yii\base\Application->run()
#26 /Applications/MAMP/htdocs/hack/y3/public/index.php(15): {closure}()
```
<img width="338" alt="bildschirmfoto 2018-09-10 um 10 15 09" src="https://user-images.githubusercontent.com/11181579/45285349-43a0fd00-b4e3-11e8-8fe1-a9b83eda68f2.png">

It appears in [active-record](https://github.com/yiisoft/active-record/blob/a3715c22a4617cac4fc05cbafdefd726f1df7716/composer.json#L69),  db, view and yii-dataview.

**Comment by hiqsol** [comment]
Thank you!
Seems fixed everywhere.
